### ISSUE TITLE
Green light at boot

### ISSUE THREAD

**Issue by Ezrae** [DC540-Nova/DC30-Tarot-Badge#1]
Hi! I received the Tarot badge yesterday and it is beautiful, thank you!! Unfortunately, out of the box, I'm running into the green light at boot problem that's mentioned in the Hardware troubleshooting section of the wiki. I've tried both steps -- flashing updated firmware, and creating clean SD cards (both the SD card/adapter that came with it, and several of my spares) but that hasn't worked.  I'm wondering if there are any other troubleshooting steps you recommend? Thanks!

**Comment by mytechnotalent** [comment]
Hi @Ezrae did you see on the main page that you need to copy all of these files and folders over to the SD card?

```
Copy Files/Folders To SD Card

Marseilles-Pitisci
Rider-Waite
Shitty-Deck
bad_advice
3Hats.raw
Unispace12x24.c
dc540_logo.raw
```

**Comment by Ezrae** [comment]
Hi! Yes I used the file list on the main page to both rebuild the SD card it came with, and to create new ones with my spare SD cards.

I noticed this morning that SD card that came with the badge filesystem was "W95 FAT32" (16bit). When I tested yesterday on my spare SD cards I was using the 32bit FAT32. I just tried again with the same filesystem as the one that came with it but I'm still getting the same green light.

```
ezrae@ezrae-lt:/media/ezrae/TAROT$ ls -la 
total 436
drwxr-xr-x  6 ezrae ezrae  16384 Dec 31  1969 .
drwxr-x---+ 3 root     root       4096 Sep 21 07:28 ..
-rw-r--r--  1 ezrae ezrae 153600 Sep 21 07:17 3Hats.raw
drwxr-xr-x  2 ezrae ezrae  16384 Sep 21 07:17 bad_advice
-rw-r--r--  1 ezrae ezrae 153600 Sep 21 07:17 dc540_logo.raw
drwxr-xr-x  2 ezrae ezrae  16384 Sep 21 07:17 Marseilles-Pitisci
drwxr-xr-x  2 ezrae ezrae  16384 Sep 21 07:17 Rider-Waite
drwxr-xr-x  2 ezrae ezrae  16384 Sep 21 07:18 Shitty-Deck
-rw-r--r--  1 ezrae ezrae  24248 Sep 21 07:18 Unispace12x24
```.c

**Comment by mytechnotalent** [comment]
Are you In the Discord?  Try the new firmware as there is a test that diagnoses issue on the screen.

**Comment by Ezrae** [comment]
I'll try posting in Discord, thanks!

**Comment by mytechnotalent** [comment]
@Ezrae excited you got it working!  Any issues please reach out and thank you for being so patient!
